# Generated by Django 5.2.13 on 2026-04-21 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('prix', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('estDisponible', models.BooleanField(default=True)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salles.salle')),
            ],
        ),
    ]
