# Generated by Django 5.2.13 on 2026-05-07 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilite',
            name='salle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilite', to='salles.salle'),
        ),
    ]
